@baseUrl = http://localhost:3000
@authBaseUrl= http://localhost:3001

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjk0MjI3M2QxOTM4NDdhMmUxZWJjZGYiLCJpYXQiOjE2NTgzNjM3OTAsImV4cCI6MTY1ODM2NzM5MH0.oRu50m4NxHHdsvdk6iUhvOBwWE4W00oNDaLlq0D94XU


# @name Login
POST {{authBaseUrl}}/api/auth/auth.signIn HTTP/1.1
Content-Type: application/json

{
  "email": "francoadinapoli@gmail.com",
  "password": "Fa42904558;"
}


# @name PublicationFindAll
GET {{baseUrl}}/api/travelers/publication.findAll HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


