version: "3"

networks:
  travelers_net:

services:

  travelers-auth-api:
    container_name: travelers-auth-api
    build:
      context: .
      dockerfile: ./packages/auth-api/Dockerfile.ci
    environment:
      - PORT=3000
      - MONGO_DB_URI='mongodb://travelers:travelers@travelers_net:27017/travelers?authSource=admin'
      - JWT_SECRET_KEY='topSecretKey'


    links:
      - "mongo:travelers_net"
    networks:
      travelers_net:
    depends_on:
      - mongo

  mongo:
      image: mongo:4.4
      container_name: mongo-be-travelers-app
      environment:
        MONGO_INITDB_ROOT_USERNAME: travelers
        MONGO_INITDB_ROOT_PASSWORD: travelers
      volumes:
        - ./.mongo_data:/data/db2
      ports:
        - "27017:27017"
      networks:
        travelers_net:

volumes:
  mongo: