name: CI

on:
  discussion:
    types: ['ready for review']
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install
        run: npm ci
      
      - name: Clean
        run: npm run clean

      - name: Bootstrap
        run: npm run bootstrap
      
      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      